### ISSUE TITLE
no longer minimal blockchain

### ISSUE THREAD

**Issue by lukepark327** [lukepark327/onechain#23]

**Comment by twodude** [comment]
There are four steps to implement complete 'onechain'
1. minimal functional blockchain
2. communication-able blockchain
3. consensus-driven blockchain
4. identifiable blockchain

**Comment by lukepark327** [comment]
There are four steps to implement complete 'onechain'
1. minimal functional blockchain
2. communication-able blockchain
3. consensus-driven blockchain
4. identifiable blockchain
