### ISSUE TITLE
Update "How to Use" video

### ISSUE THREAD

**Issue by zzinny** [lukepark327/onechain#35]
In the "How to Use" video, the route "/addpeer" is demonstrated instead of "/addPeers".

Also the example body contents should be {"peers":["address1", "address2",...]} or {"peers":["address1"]} not {"peer":"address1"} if the correct route "/addPeers" will be shown.

Thanks!

**Comment by lukepark327** [comment]
Thx! The current video is based on onechain V1... but now V2.
Please refer to the text mainly until updating.

👍
