### ISSUE TITLE
Why does the output order of data and header change when using json.tool?

### ISSUE THREAD

**Issue by Dust-J** [lukepark327/onechain#40]
![image](https://user-images.githubusercontent.com/29055942/65953864-d0688100-e47f-11e9-929d-9b8a967439c1.png)
on Windows

**Comment by lukepark327** [comment]
* Ref. this: https://stackoverflow.com/questions/54559051/how-or-can-i-get-python-mjson-tool-to-maintain-the-order-of-the-attributes and this: https://python.flowdas.com/library/json.html#cmdoption-json-tool-sort-keys

* If you use old version pf python, plz try >= 3.7 or —sort-keys=False option

`blah blah | python -m json.tool —sort-keys=False`

**Comment by Dust-J** [comment]
The command `—sort-keys=False` did not work because it was < 3.5, but the first link was helpful.
![image](https://user-images.githubusercontent.com/29055942/65957900-078f6000-e489-11e9-86a7-7d99f8555d07.png)

Ok, now I'll use version >= 3.7.
Thx!
